[package]
name = "qq-bot"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "qq-bot"
path = "src/main.rs"

[dependencies]
proc_qq = { git = "https://github.com/niuhuan/rust_proc_qq.git", branch = "next" }
tracing = "0.1"
tracing-subscriber = "0.3"
tokio = "1.28"